import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight, Box, FileText, Layers3, MonitorSmartphone } from 'lucide-react'
import { FeatureAtlas } from './feature-atlas'
import { NarrativeWalkthrough } from './narrative-walkthrough'
import { WorkspacePreview } from './workspace-preview'
import styles from './sections.module.css'

const steps = [
  { number: '01', name: 'Frame', title: 'Give the idea a size.', detail: 'Start with the space you actually need: desktop, tablet or mobile.', icon: MonitorSmartphone },
  { number: '02', name: 'Build', title: 'Place the structure.', detail: 'Build by hand with semantic blocks, or plan a scoped AI change.', icon: Box },
  { number: '03', name: 'Refine', title: 'Set the direction.', detail: 'Apply a preset or your DESIGN.md without losing the page hierarchy.', icon: Layers3 },
  { number: '04', name: 'Handoff', title: 'Carry it forward.', detail: 'Export and share a structure the next tool can understand.', icon: FileText },
] as const

const plans = [
  { name: 'Solo', price: '$5', audience: 'For one person shaping the first version.', items: ['Semantic block workspace', 'Responsive frame workflow', 'Your own model provider'], highlight: false },
  { name: 'Maker', price: '$10', audience: 'For an active design-to-code practice.', items: ['Everything in Solo', 'Preset and DESIGN.md context', 'More room for project iterations'], highlight: true },
  { name: 'Studio', price: '$19', audience: 'For deeper projects and handoff needs.', items: ['Everything in Maker', 'Structured share and export', 'Space for a broader project portfolio'], highlight: false },
] as const

export function LandingSections() {
  return <>
    <section className={`${styles.section} ${styles.proof}`} aria-labelledby="proof-heading"><div className={styles.container}><div className={styles.intro}><span className={styles.kicker}>THE WORKSPACE</span><h2 id="proof-heading">See the structure, not just the surface.</h2><p>One view for your frames, blocks, AI context and layout decisions. Nothing gets lost behind a prompt.</p></div>
      {/* PLACEHOLDER_ASSET — Ideal: genuine dark FORME workspace capture showing desktop/mobile frames and inspector; role: product proof; ratio: 16:10. This reconstructed UI is illustrative until the real editor exists. */}
      <div className={styles.proofVisual}><WorkspacePreview compact /><div className={styles.proofLegend}><span>Semantic canvas</span><span>Scoped Composer</span><span>Responsive frames</span></div></div></div></section>

    <NarrativeWalkthrough />
    <FeatureAtlas />

    <section className={`${styles.section} ${styles.providerSection}`} aria-labelledby="provider-heading"><div className={`${styles.container} ${styles.split}`}><div className={styles.copy}><span className={styles.kicker}>YOUR MODEL</span><h2 id="provider-heading">Bring the model you already use.</h2><p>Connect a provider when the workspace opens; models appear only after your own credentials are validated. No model catalog is assumed here.</p><Link href="/product" className={styles.textLink}>Explore the product <ArrowUpRight size={16} aria-hidden="true" /></Link></div><div className={styles.providerStage} aria-label="Illustrative provider settings preview, not an active connection form"><div className={styles.providerTop}>Provider connections <span>Illustrative preview</span></div><div className={styles.providerRow}><span>OpenAI</span><span>BYOK · planned</span></div><div className={styles.providerRow}><span>Anthropic / Claude</span><span>BYOK · planned</span></div><div className={styles.providerRow}><span>Google / Gemini</span><span>BYOK · planned</span></div><div className={styles.providerRow}><span>OpenAI-Compatible</span><span>Custom base URL · planned</span></div><div className={styles.providerRow}><span>Ignix</span><span>Coming Soon</span></div><div className={styles.providerBottom}>Model discovery requires a valid real connection.</div></div></div></section>

    <section className={`${styles.section} ${styles.workflowSection}`} aria-labelledby="workflow-heading"><div className={styles.container}><div className={styles.intro}><span className={styles.kicker}>FROM IDEA TO HANDOFF</span><h2 id="workflow-heading">Stay with the same artifact.</h2><p>A clear progression from a blank frame to a structured handoff.</p></div><div className={styles.workflowCards}>{steps.map(({ number, name, title, detail, icon: Icon }) => <article className={styles.workflowCard} key={name}><div className={styles.workflowCardHead}><span>{number} / {name.toUpperCase()}</span><Icon size={21} strokeWidth={1.5} aria-hidden="true" /></div><div className={styles.workflowSketch} aria-hidden="true"><i /><i /><i /></div><div><h3>{title}</h3><p>{detail}</p></div></article>)}</div><Link href="/workflow" className={styles.textLink}>See the full workflow <ArrowUpRight size={16} aria-hidden="true" /></Link></div></section>

    <section className={`${styles.section} ${styles.pricingSection}`} aria-labelledby="pricing-heading"><div className={styles.container}><div className={styles.pricingHead}><div><span className={styles.kicker}>PRICING PROPOSAL</span><h2 id="pricing-heading">Start small. Grow with the work.</h2></div><p>Three planned monthly subscriptions for a proprietary workspace. Proposed prices, no checkout yet. BYOK provider usage is billed separately by your model provider.</p></div><div className={styles.planGrid}>{plans.map((plan) => <article className={`${styles.plan} ${plan.highlight ? styles.planFeatured : ''}`} key={plan.name}><div className={styles.planTop}><h3>{plan.name}</h3>{plan.highlight && <span>For active builders</span>}</div><p className={styles.planPrice}><strong>{plan.price}</strong><span> USD / editor / month</span></p><p className={styles.planAudience}>{plan.audience}</p><ul>{plan.items.map(item => <li key={item}>{item}</li>)}</ul><Link href="/pricing">Review proposed plan <ArrowUpRight size={15} aria-hidden="true" /></Link></article>)}</div><p className={styles.priceNote}>Pricing and feature limits are proposals, not an active offer. No payment is collected.</p></div></section>

    <section className={`${styles.section} ${styles.collectionSection}`} aria-labelledby="collection-heading"><div className={`${styles.container} ${styles.collectionLayout}`}><div><span className={styles.kicker}>BEYOND FORME</span><h2 id="collection-heading">More from Mavent.</h2><p>Product details, screenshots, and official links will be added from the source information provided by Mavent.</p><Link href="/mavent-products" className={styles.textLink}>View Mavent products <ArrowRight size={16} aria-hidden="true" /></Link></div><div className={styles.collectionNames}><span>FORME</span><span>Vulpix Mavent</span><span>Ignix</span><span>AnyMD</span><span>Moxa</span></div></div></section>

    <section className={`${styles.section} ${styles.faqSection}`} aria-labelledby="faq-heading"><div className={`${styles.container} ${styles.faqLayout}`}><div><span className={styles.kicker}>FREQUENTLY ASKED QUESTIONS</span><h2 id="faq-heading">The useful details.</h2></div><div className={styles.faqItems}><details><summary>Can I try the workspace now?</summary><p>You can click through the local preview above. Project accounts, cloud saving, and the full editor are in development; this preview does not save a project.</p></details><details><summary>Can I use my own AI model?</summary><p>BYOK provider connections are planned. Model choices will appear after real credential validation, not from a permanent hardcoded list.</p></details><details><summary>Does FORME generate DESIGN.md automatically?</summary><p>Not yet. Upload, paste, and manual editing are in the product scope; automatic generation is Coming Soon.</p></details><details><summary>Can I import a website?</summary><p>Website crawling is Coming Soon. It will extract structural principles into editable nodes, not copy a site pixel by pixel.</p></details><details><summary>Is FORME open source? Can I subscribe today?</summary><p>FORME is a proprietary product. Monthly subscription prices shown here are proposals; sign-in and paid checkout are not live yet.</p></details></div></div></section>

    <section className={styles.closing} aria-labelledby="closing-heading"><div className={`${styles.container} ${styles.closingLayout}`}><div><span className={styles.kicker}>FORME BY MAVENT</span><h2 id="closing-heading">Make the next thing<br />make sense.</h2><p>Start with the structure you want to build. Explore a real preview of the space where that work will happen.</p><Link href="/workspace" className={styles.primaryAction}>Try the workspace preview <ArrowUpRight size={17} aria-hidden="true" /></Link></div><div className={styles.closingVisual} aria-hidden="true"><Image src="/brand/forme/forme-logo-symbol.png" alt="" width={189} height={174} style={{ width: 100, height: 'auto' }} /><div><span>01</span><span>Frame</span><span>02</span><span>Structure</span><span>03</span><span>Direction</span></div></div></div></section>
  </>
}

export function SiteFooter() {
  return <footer className={styles.footer}><div className={styles.container}><div className={styles.footerTop}><div className={styles.footerBrand}><Image src="/brand/forme/forme-logo-primary.png" alt="FORME by Mavent" width={598} height={176} /><p>Shape the interface before you build it.</p></div><div className={styles.footerLinks}><div><strong>Product</strong><Link href="/workspace">Workspace preview</Link><Link href="/product">Product</Link><Link href="/pricing">Pricing</Link></div><div><strong>Explore</strong><Link href="/workflow">Workflow</Link><Link href="/design-md">DESIGN.md · Soon</Link><Link href="/crawl">Website import · Soon</Link></div><div><strong>Mavent</strong><Link href="/mavent-products">All products</Link><Link href="/about">About</Link></div><div><strong>Legal</strong><Link href="/privacy">Privacy status</Link></div></div></div><div className={styles.footerBottom}><span>© 2026 Mavent</span><span>Made for the work before code.</span></div></div></footer>
}
